disabled_rules:
  - identifier_name
  - cyclomatic_complexity
  - line_length
opt_in_rules:
included:
  - Sources/ 
excluded:
  - Sources/Generated/
function_parameter_count:
  warning: 10
  error: 15
large_tuple:
  warning: 4
type_body_length:
  warning: 300
  error: 350
function_body_length: 80
file_length:
  warning: 400
  error: 800
reporter: "xcode"

