name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [macos-10.15]

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: brew install boost ninja
    - name: Install Android Dependencies
      run: |
        $ANDROID_HOME/tools/bin/sdkmanager --verbose "cmake;3.10.2.4988404" "ndk;21.2.6472646"
        $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-26;google_apis;x86"
    - name: Accept Licenses
      run: echo -e "y\ny\ny\ny\ny\n" | $ANDROID_HOME/tools/bin/sdkmanager --licenses
    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v1.1.2
      with:
        path: build/local
        key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-dependencies') }}
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
      if: steps.internal_cache.outputs.cache-hit != 'true'
    - name: Run test
      run: |
        tools/generate-files
        tools/android-test
