name: iOS Release

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

jobs:
  release:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        brew install boost ninja xcodegen
    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v1.1.2
      with:
        path: build/local
        key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-dependencies') }}
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
      if: steps.internal_cache.outputs.cache-hit != 'true'
    - name: Generate files
      run: tools/generate-files
    - name: Build and release
      run: |
        tools/ios-release
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.WC_GITHUB_TOKEN }}
        GITHUB_USER: ${{ secrets.WC_GITHUB_USER }}
