name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        # build-essential libboost-all-dev clang-9 ruby-full cmake
        sudo apt-get install libc++-dev libc++abi-dev ninja-build lcov llvm clang-tidy
    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v1.1.2
      with:
        path: build/local
        key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-dependencies') }}
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
      if: steps.internal_cache.outputs.cache-hit != 'true'
    - name: Code generation
      run: |
        tools/generate-files
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
    - name: Prepare build with lint
      if: github.ref == 'refs/heads/master'
      run: |
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=${BOOST_ROOT_1_72_0} -DCLANG_TIDY=ON -DCODE_COVERAGE=ON -DCLANG_ASAN=ON
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
    - name: Prepare build without lint
      if: github.ref != 'refs/heads/master'
      run: |
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=${BOOST_ROOT_1_72_0} -DCODE_COVERAGE=ON
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
    - name: Build and test
      run: |
        make -Cbuild -j12 tests TrezorCryptoTests
        build/trezor-crypto/crypto/tests/TrezorCryptoTests
        build/tests/tests tests --gtest_output=xml
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
        CK_TIMEOUT_MULTIPLIER: 4
    - name: Gather code coverage
      run: |
        sudo rm -rf coverage.info
        tools/coverage
