name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        # build-essential clang-14 libc++-dev libc++abi-dev ruby-full cmake
        sudo apt-get update && sudo apt-get install ninja-build lcov llvm-14 clang-tidy-14 libboost-all-dev --fix-missing
    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v1.1.2
      with:
        path: build/local
        key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-dependencies') }}
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
      if: steps.internal_cache.outputs.cache-hit != 'true'
    - name: Code generation
      run: |
        tools/generate-files
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
    - name: CMake (coverage/clang-tidy/clang-asan)
      if: github.ref == 'refs/heads/master'
      run: |
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON -DTW_ENABLE_CLANG_TIDY=ON -DCLANG_ASAN=ON
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
    - name: CMake (coverage)
      if: github.ref != 'refs/heads/master'
      run: |
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
    - name: Build and test
      run: |
        make -Cbuild -j12 tests TrezorCryptoTests
        build/trezor-crypto/crypto/tests/TrezorCryptoTests
        build/tests/tests tests --gtest_output=xml
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
        CK_TIMEOUT_MULTIPLIER: 4
    - name: Gather and check code coverage
      run: |
        sudo rm -rf coverage.info
        tools/coverage
