name: Typescript CI

on:
  push:
    branches: [ master ]
    paths:
      - typescript/**
  pull_request:
    branches: [ master ]
    paths:
      - typescript/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    outputs:
      publish_npm: ${{ steps.version.outputs.publish_npm }}
      publish_gpr: ${{ steps.version.outputs.publish_gpr }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
      working-directory: typescript
    - name: Build and test
      run: yarn build && yarn test
      working-directory: typescript
    - name: Check if needed to publish
      id: version
      run: |
        echo "::set-output name=publish_npm::$(tools/check-npm-version)"
        echo "::set-output name=publish_gpr::$(tools/check-gpr-version)"
      working-directory: typescript
      env:
        TOKEN: ${{secrets.GITHUB_TOKEN}}
  publish-npm:
    needs: build
    if: needs.build.outputs.publish_npm == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Publish
        run: |
          yarn install && yarn build && npm publish --access public
        working-directory: typescript
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-gpr:
    needs: build
    if: needs.build.outputs.publish_gpr == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - name: Publish
        run: |
          yarn install && yarn build && npm publish --access public
        working-directory: typescript
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
